[id="external"]

= Cairo 中的 External Functions

External Functions是可以通过其他合约或用户通过区块链上的交易外部调用的函数。它们可以改变合约的状态，因此，需要执行 gas 费用。这意味着我们可以使用 `write` 函数将数据写入合约的存储。

在 Cairo 中，使用 `#[external]` 属性定义 External Functions 。在 Solidity 中，你可以使用 `public` 或 `external` 关键字来定义类似类型的函数。

在 Vote 合约中，只有一个 External Functions ：`vote`。让我们详细了解一下：


[source,rust]
----
// @dev 提交投票（0 表示 No，1 表示 Yes）
// @param vote (u8): 投票值，0 表示 No，1 表示 Yes
// @return () : 更新存储中的投票计数，并将投票者标记为不允许再次投票
#[external]
fn vote(vote: u8) {
    // 检查投票是否有效（0 或 1）
    assert(vote == 0_u8 | vote == 1_u8, 'VOTE_0_OR_1');

    // 知道投票者是否已经投票，如果没有投票则继续
    let caller : ContractAddress = get_caller_address();
    assert_allowed(caller);

    // 标记投票者已经投票，并在存储中更新
    can_vote::write(caller, false);

    // 根据投票值（0 或 1）更新存储中的投票计数
    if (vote == 0_u8) {
        no_votes::write(no_votes::read() + 1_u8);
    }
    if (vote == 1_u8) {
        yes_votes::write(yes_votes::read() + 1_u8);
    }
}
----

`vote` 函数是一个 External Functions ，允许用户向合约提交投票（0 表示 No，1 表示 Yes）。它接受一个 `u8` 值作为输入，检查该值是否有效（0 或 1），并相应地更新存储。


[NOTE]
====
《Starknet 之书》是 Starknet 社区成员合力之作，便于社区成员学习之用。

* 无论你是否有所收获，烦请填写此问卷， https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[简单回答三个问题] ，给予我们反馈。
* 若发现任何错误，或有其他建议，请在我们的 https://github.com/starknet-edu/starknetbook/issues[Github 仓库]发起问题单 (Issues)。
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet!
____