[id="structure"]

= Internal Functions （内部函数）

Cairo 中的内部函数是只能由同一合约内的其他函数调用的函数。它们不能从合约外部或其他合约调用。在 Solidity 中，你可以使用 private 或 internal 函数来实现类似的目的。

在 Vote 合约中，内部函数定义如下：

[source,rust]
----
fn assert_allowed(address: ContractAddress) { ... }

fn _register_voters(
    voter_1: ContractAddress, voter_2: ContractAddress, voter_3: ContractAddress
) { ... }
----

`assert_allowed` 函数是一个内部函数，用于检查投票者是否已经投票。它由 `vote` 函数调用，以确保投票者只能投票一次。

`_register_voters` 函数是一个内部函数，用于注册一组投票者。它由 `register_voters` 函数调用，以注册一组投票者。

[NOTE]
====
《Starknet 之书》是 Starknet 社区成员合力之作，便于社区成员学习之用。

* 无论你是否有所收获，烦请填写此问卷， https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[简单回答三个问题] ，给予我们反馈。
* 若发现任何错误，或有其他建议，请在我们的 https://github.com/starknet-edu/starknetbook/issues[Github 仓库]发起问题单 (Issues)。
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet!
____