= 前端开发

====
贡献者：您的贡献可以极大地提高本章的深度和实用性。我们特别寻求使用 starknet-react 与 starknet.js 一起创建简单 dApps 的示例。如果您已经构建了一些东西或者有心得体会，我们鼓励您在我们的 https://github.com/starknet-edu/starknetbook/[GitHub 仓库]上提交 PR。您的专业知识将帮助扩展我们的集体知识，并让区块链技术更容易为大家所接受。感谢您考虑为这个开源项目做出贡献。

====

在 starknet 生态中存在着几种用于构建应用前端的工具。最受欢迎的工具有：


* https://github.com/apibara/starknet-react[starknet-react] (https://apibara.github.io/starknet-react[文档]): Starknet 的 React 钩子集合。它受到 https://github.com/tmm/wagmi[wagmi] 的启发， 由 https://github.com/0xs34n/starknet.js[starknet.js] 提供支持。
* https://github.com/0xs34n/starknet.js[starknet.js]: 一个用于与 Starknet 合约交互的 JavaScript 库。它相当于以太坊的  https://web3js.org/[web3.js]。


[NOTE]
====
《Starknet 之书》是 Starknet 社区成员合力之作，便于社区成员学习之用。

* 无论你是否有所收获，烦请填写此问卷， https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[简单回答三个问题] ，给予我们反馈。
* 若发现任何错误，或有其他建议，请在我们的 https://github.com/starknet-edu/starknetbook/issues[Github 仓库]发起问题单 (Issues)。
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____