[id="vue-stark-boil"]

= Vue Stark Boil

====
贡献者：我们希望添加一个关于如何使用 Starknet Vue 的具体示例。如果您有一个使用 Starknet React 的项目，请提交 PR。
====

Starknet 生态系统为 Vue 和 React 提供了合适的框架。对于那些喜欢 Vue 的人来说，由 https://github.com/dontpanicdao[Don't Panic DAO] 团队开发的 vue-stark-boil 是一个很好的选择。

首先，从 https://github.com/dontpanicdao/vue-stark-boil[此处] 将项目克隆到您的设备上。要深入了解 Vue，请访问他们的 https://vuejs.org/[网站]。vue-stark-boil 模板支持各种功能，如连接到钱包，监听帐户更改和调用合约。

在克隆项目后，请确保通过在终端运行以下命令安装所有依赖项：

[source, bash]
----
npm install
----


[NOTE]
====
《Starknet 之书》是 Starknet 社区成员合力之作，便于社区成员学习之用。

* 无论你是否有所收获，烦请填写此问卷， https://a.sprig.com/WTRtdlh2VUlja09lfnNpZDo4MTQyYTlmMy03NzdkLTQ0NDEtOTBiZC01ZjAyNDU0ZDgxMzU=[简单回答三个问题] ，给予我们反馈。
* 若发现任何错误，或有其他建议，请在我们的 https://github.com/starknet-edu/starknetbook/issues[Github 仓库]发起问题单 (Issues)。
====

== Contributing

[quote, The Starknet Community]
____
*Unleash Your Passion to Perfect StarknetBook*

StarknetBook is a work in progress, and your passion, expertise, and unique insights can help transform it into something truly exceptional. Don't be afraid to challenge the status quo or break the Book! Together, we can create an invaluable resource that empowers countless others.

Embrace the excitement of contributing to something bigger than ourselves. If you see room for improvement, seize the opportunity! Check out our https://github.com/starknet-edu/starknetbook/blob/main/CONTRIBUTING.adoc[guidelines] and join our vibrant community. Let's fearlessly build Starknet! 
____
